apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: prometheus-operator-prometheus
  labels:
    app.kubernetes.io/name: prometheus-operator-prometheus
    app.kubernetes.io/instance: prometheus-operator
  namespace: monitoring
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/instance: prometheus-operator
