apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator-prometheus
  labels: &labels
    app.kubernetes.io/name: prometheus-operator-prometheus
    app.kubernetes.io/instance: prometheus-operator
  namespace: monitoring
spec:
  selector:
    matchLabels:
      <<: *labels
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: web
      path: /metrics
