---
apiVersion: v1
kind: Pod
metadata:
  name: backups
  namespace: minecraft
spec:
  containers:
    - name: backups
      image: ubuntu:latest
      tty: true
      stdin: true
      volumeMounts:
        - name: vanilla
          mountPath: /vanilla
        - name: backup
          mountPath: /backup
  volumes:
    - name: vanilla
      persistentVolumeClaim:
        claimName: vanilla
    - name: backup
      persistentVolumeClaim:
        claimName: vanilla-backup
