---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: guardians.hannahs.family
  namespace: kube-system
spec:
  endpoints:
    - dnsName: guardians.hannahs.family
      recordType: CNAME
      targets:
        - tapu-bulu.hannahs.family
        - tapu-fini.hannahs.family
        - tapu-koko.hannahs.family
        - tapu-lele.hannahs.family
