---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-vault
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kubernetes-vault
    app.kubernetes.io/instance: kubernetes-vault
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubernetes-vault
  labels:
    app.kubernetes.io/name: kubernetes-vault
    app.kubernetes.io/instance: kubernetes-vault
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources:
      - endpoints
    verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubernetes-vault
  labels:
    app.kubernetes.io/name: kubernetes-vault
    app.kubernetes.io/instance: kubernetes-vault
subjects:
  - kind: ServiceAccount
    name: kubernetes-vault
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kubernetes-vault
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-vault
  namespace: kube-system
  labels: &labels
    app.kubernetes.io/name: kubernetes-vault
    app.kubernetes.io/instance: kubernetes-vault
spec:
  clusterIP: None
  selector:
    <<: *labels
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-vault
  namespace: kube-system
  labels: &labels
    app.kubernetes.io/name: kubernetes-vault
    app.kubernetes.io/instance: kubernetes-vault
spec:
  replicas: 3
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      serviceAccountName: kubernetes-vault
      containers:
        - name: kubernetes-vault
          image: boostport/kubernetes-vault
          imagePullPolicy: Always
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config-volume
              mountPath: /kubernetes-vault
            - name: ca
              mountPath: /etc/ssl/certs/hannahs.family.ca.cert.pem
      volumes:
        - name: config-volume
          secret:
            secretName: kubernetes-vault
        - name: ca
          hostPath:
            path: /etc/ssl/certs/hannahs.family.ca.cert.pem
            type: File
