---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: vault
  labels: &labels
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      <<: *labels

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
  namespace: kube-system
data:
  config.hcl: |
    ui = true

    listener "tcp" {
      address = "[::]:8200"
      cluster_address = "[::]:8201"
      tls_cert_file = "/vault/tls/cert.pem"
      tls_key_file = "/vault/tls/key.pem"
    }

    telemetry {
      disable_hostname = true
      prometheus_retention_time = "24h"
    }

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: kube-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: vault-server-binding
  namespace: kube-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: kube-system

---
apiVersion: v1
kind: Service
metadata:
  name: vault
  labels: &labels
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  namespace: kube-system
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: https
      port: 8200
      targetPort: 8200
    - name: internal
      port: 8201
      targetPort: 8201
  selector:
    <<: *labels

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  labels: &labels
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
  annotations:
    fluxcd.io/tag.consul-agent: semver:~1
    fluxcd.io/tag.vault: semver:~1
    fluxcd.io/automated: "true"
  namespace: kube-system
spec:
  serviceName: vault
  podManagementPolicy: Parallel
  replicas: 3
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  <<: *labels
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      serviceAccountName: vault
      containers:
        - name: consul-agent
          image: consul:1.6.1
          args:
            - agent
            - -config-dir=/etc/consul/config
            - -encrypt=$(GOSSIP_KEY)
          env:
            - name: GOSSIP_KEY
              valueFrom:
                secretKeyRef:
                  name: consul
                  key: gossip-key
          volumeMounts:
            - name: consul-config
              mountPath: /etc/consul/config
              readOnly: true
            - name: consul-agent-datadir
              mountPath: /var/lib/consul
        - name: vault
          image: vault:1.2.3
          command:
            - vault
          args:
            - server
            - -config=/vault/config
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VAULT_ADDR
              value: https://127.0.0.1:8200
            - name: VAULT_API_ADDR
              value: https://$(POD_NAME).vault:8200
            - name: SKIP_CHOWN
              value: "true"
            - name: VAULT_CAPATH
              value: /etc/ssl/certs/hannahs.family.ca.cert.pem
          volumeMounts:
            - name: ca
              mountPath: /etc/ssl/certs/hannahs.family.ca.cert.pem
              readOnly: true
            - name: vault-config
              mountPath: /vault/config
              readOnly: true
            - name: vault-tls
              mountPath: /vault/tls
              readOnly: true
          ports:
            - containerPort: 8200
              name: https
            - containerPort: 8201
              name: internal
            - containerPort: 8202
              name: replication
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
          securityContext:
            privileged: true
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -ec
                - vault status -tls-skip-verify
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 5
      volumes:
        - name: ca
          hostPath:
            path: /etc/ssl/certs/hannahs.family.ca.cert.pem
            type: File
        - name: consul-config
          configMap:
            name: consul
        - name: vault-config
          projected:
            sources:
              - configMap:
                  name: vault
              - secret:
                  name: vault
                  items:
                    - key: consul.hcl
                      path: consul.hcl
        - name: vault-tls
          secret:
            secretName: vault
            items:
              - key: cert.pem
                path: cert.pem
              - key: key.pem
                path: key.pem
  volumeClaimTemplates:
    - metadata:
        name: consul-agent-datadir
        labels:
          <<: *labels
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: kube-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: kube-system

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vault-http
  namespace: kube-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`vault.hannahs.family`)
      kind: Rule
      middlewares:
        - name: https-redirect
          namespace: default
      services:
        - name: vault
          port: 8200

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vault-https
  namespace: kube-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`vault.hannahs.family`)
      kind: Rule
      services:
        - name: vault
          port: 8200
  tls:
    certResolver: default

---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: vault-ui
  namespace: kube-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
spec:
  endpoints:
    - dnsName: vault.hannahs.family
      recordType: CNAME
      targets:
        - traefik.hannahs.family
