apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-kube-proxy
  labels:
    jobLabel: kube-proxy
    app.kubernetes.io/name: prometheus-operator-kube-proxy
    app.kubernetes.io/instance: prometheus-operator
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10249
      protocol: TCP
  selector:
    k8s-app: kube-proxy
  type: ClusterIP
