---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rook-ceph-block
  namespace: rook-ceph
spec:
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-block
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ceph.rook.io/block
parameters:
  blockPool: rook-ceph-block
  clusterNamespace: rook-ceph
