---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.4-20190917
  dataDirHostPath: /var/lib/rook
  mgr:
    modules:
      - name: pg_autoscaler
        enabled: true
  mon:
    count: 3
  dashboard:
    enabled: true
    port: 8443
  storage:
    useAllNodes: true
    useAllDevices: false
    directories:
      - path: /srv/rook-ceph
  resources:
    mon:
      limits: &resources
        cpu: 250m
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 128Mi
    mgr:
      limits: &resources
        cpu: 100m
        memory: 512Mi
      requests:
        cpu: 25m
        memory: 128Mi
    osd:
      limits: &resources
        cpu: 250m
        memory: 2Gi
      requests:
        <<: *resources
        cpu: 25m
    prepareosd:
      limits:
        cpu: 100m
        memory: 100Mi
