---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
  labels:
    operator: rook
    storage-backend: ceph
  annotations:
    fluxcd.io/tag.rook-ceph-operator: semver:~1.1
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: rook-ceph-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: rook-ceph-operator
    spec:
      serviceAccountName: rook-ceph-system
      containers:
        - name: rook-ceph-operator
          image: rook/ceph:v1.1.4
          args: ["ceph", "operator"]
          volumeMounts:
            - mountPath: /var/lib/rook
              name: rook-config
            - mountPath: /etc/ceph
              name: default-config-dir
          resources:
            limits: &resources
              memory: 128Mi
              cpu: 1000m
            requests:
              <<: *resources
              cpu: 10m
          env:
            - name: ROOK_CURRENT_NAMESPACE_ONLY
              value: "true"
            - name: ROOK_ALLOW_MULTIPLE_FILESYSTEMS
              value: "false"
            - name: ROOK_LOG_LEVEL
              value: INFO
            - name: ROOK_CSI_KUBELET_DIR_PATH
              value: /var/lib/rancher/k3s/agent/kubelet
            - name: ROOK_CEPH_STATUS_CHECK_INTERVAL
              value: "60s"
            - name: ROOK_MON_HEALTHCHECK_INTERVAL
              value: "45s"
            - name: ROOK_MON_OUT_TIMEOUT
              value: "600s"
            - name: ROOK_DISCOVER_DEVICES_INTERVAL
              value: "60m"
            - name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
              value: "false"
            - name: ROOK_ENABLE_SELINUX_RELABELING
              value: "false"
            - name: ROOK_ENABLE_FSGROUP
              value: "true"
            - name: ROOK_DISABLE_DEVICE_HOTPLUG
              value: "true"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: rook-config
          emptyDir: {}
        - name: default-config-dir
          emptyDir: {}
