apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-operator-kube-scheduler
  labels:
    k8s-app: kube-scheduler
    app.kubernetes.io/name: prometheus-operator-kube-scheduler
    app.kubernetes.io/instance: prometheus-operator
  namespace: kube-system
subsets:
  - addresses:
      - ip: 104.225.223.46
    ports:
      - name: http-metrics
        port: 10251
        protocol: TCP
