---
# Source: prometheus-operator/templates/alertmanager/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-prometheus-operator-alertmanager
  namespace: monitoring
  labels:
    app: prometheus-operator-alertmanager

    chart: prometheus-operator-6.8.2
    release: "prometheus-operator"
    heritage: "Tiller"
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    receivers:
      - name: "null"
    route:
      group_by:
        - job
      group_interval: 5m
      group_wait: 30s
      receiver: "null"
      repeat_interval: 12h
      routes:
        - match:
            alertname: Watchdog
          receiver: "null"
