kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-operator-operator-psp
  labels:
    app.kubernetes.io/name: prometheus-operator-operator
    app.kubernetes.io/instance: prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator-operator-psp
subjects:
  - kind: ServiceAccount
    name: prometheus-operator-operator
    namespace: monitoring
