apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator-operator
  labels: &labels
    app.kubernetes.io/name: prometheus-operator-operator
    app.kubernetes.io/instance: prometheus-operator
  namespace: monitoring
spec:
  endpoints:
    - port: http
      honorLabels: true
  selector:
    matchLabels:
      <<: *labels
  namespaceSelector:
    matchNames:
      - monitoring
