apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-kube-state-metrics
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/instance: prometheus-operator
  annotations:
    prometheus.io/scrape: "true"
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
  selector:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/instance: prometheus-operator
