---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    app.kubernetes.io/instance: kured
    app.kubernetes.io/name: kured
  name: kured
  namespace: kube-system
spec:
  allowedCapabilities:
    - "*"
  fsGroup:
    rule: RunAsAny
  hostPID: true
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - "*"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: kured
    app.kubernetes.io/name: kured
  name: kured
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: kured
    app.kubernetes.io/name: kured
  name: kured
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - delete
      - get
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: kured
    app.kubernetes.io/name: kured
  name: kured
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kured
subjects:
  - kind: ServiceAccount
    name: kured
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: kured
    app.kubernetes.io/name: kured
  name: kured
  namespace: kube-system
rules:
  - apiGroups:
      - apps
    resourceNames:
      - kured
    resources:
      - daemonsets
    verbs:
      - update
  - apiGroups:
      - policy
    resourceNames:
      - kured
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: kured
    app.kubernetes.io/name: kured
  name: kured
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kured
subjects:
  - kind: ServiceAccount
    name: kured
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kured
  namespace: kube-system
  labels: &labels
    app.kubernetes.io/instance: kured
    app.kubernetes.io/name: kured
  annotations:
    fluxcd.io/tag.kured: regexp:^master-
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - args:
            - --ds-name=kured
            - --ds-namespace=kube-system
            - --start-time=3am
            - --end-time=7am
            - --time-zone=America/Phoenix
            - --prometheus-url=http://prometheus-k8s.monitoring.svc:9090
            - --alert-filter-regexp=^(Watchdog|RebootRequired)$
          command:
            - /usr/bin/kured
          env:
            - name: KURED_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8080
              name: metrics
          image: weaveworks/kured:master-4beddb5
          imagePullPolicy: Always
          name: kured
          resources:
          securityContext:
            privileged: true
      hostPID: true
      restartPolicy: Always
      serviceAccountName: kured
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
---
apiVersion: v1
kind: Service
metadata:
  name: kured
  namespace: kube-system
  labels: &labels
    app.kubernetes.io/instance: kured
    app.kubernetes.io/name: kured
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 8080
  selector:
    <<: *labels

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kured
  namespace: kube-system
  labels: &labels
    app.kubernetes.io/instance: kured
    app.kubernetes.io/name: kured
spec:
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      <<: *labels
