---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: memcached
  labels: &labels
    app.kubernetes.io/name: memcached
    app.kubernetes.io/instance: memcached
  namespace: kube-system
spec:
  selector:
    matchLabels:
      <<: *labels
  maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels: &labels
    app.kubernetes.io/name: memcached
    app.kubernetes.io/instance: memcached
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9150"
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: memcache
      port: 11211
      targetPort: memcache
    - name: metrics
      port: 9150
      targetPort: metrics
  selector:
    <<: *labels

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
  labels: &labels
    app.kubernetes.io/name: memcached
    app.kubernetes.io/instance: memcached
  annotations:
    fluxcd.io/tag.memcached: regexp:^1\.\d+\.\d+-alpine$
    fluxcd.io/tag.metrics: semver:~0
    fluxcd.io/automated: "true"
  namespace: kube-system
spec:
  serviceName: memcached
  selector:
    matchLabels:
      <<: *labels
  podManagementPolicy: Parallel
  replicas: 2
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      securityContext:
        fsGroup: 1001
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  <<: *labels
      containers:
        - name: memcached
          image: memcached:1.5.19-alpine
          imagePullPolicy: Always
          ports:
            - name: memcache
              containerPort: 11211
          livenessProbe:
            tcpSocket:
              port: memcache
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: memcache
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            limits: &resources
              cpu: 50m
              memory: 1Gi
            requests:
              <<: *resources
        - name: metrics
          image: quay.io/prometheus/memcached-exporter:v0.6.0
          securityContext:
            runAsUser: 1001
          ports:
            - name: metrics
              containerPort: 9150
