apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-operator-admission-create
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels: &labels
    app.kubernetes.io/name: prometheus-operator-admission-create
    app.kubernetes.io/instance: prometheus-operator
  namespace: monitoring
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      name: prometheus-operator-admission-create
      labels:
        <<: *labels
    spec:
      containers:
        - name: create
          image: jettech/kube-webhook-certgen:v1.0.0
          args:
            - create
            - --host=prometheus-operator-operator,prometheus-operator-operator.monitoring.svc
            - --namespace=monitoring
            - --secret-name=prometheus-operator-admission
      restartPolicy: OnFailure
      serviceAccountName: prometheus-operator-admission
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
