apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    jobLabel: node-exporter
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/instance: prometheus-operator
  name: psp-prometheus-operator-prometheus-node-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-prometheus-operator-prometheus-node-exporter
subjects:
  - kind: ServiceAccount
    name: prometheus-operator-prometheus-node-exporter
    namespace: monitoring
