apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    jobLabel: node-exporter
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/instance: prometheus-operator
  name: prometheus-operator-prometheus-node-exporter
  namespace: monitoring
spec:
  privileged: false
  volumes:
    - configMap
    - emptyDir
    - projected
    - secret
    - downwardAPI
    - persistentVolumeClaim
    - hostPath
  hostNetwork: true
  hostIPC: false
  hostPID: true
  hostPorts:
    - min: 0
      max: 65535
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - min: 0
        max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 0
        max: 65535
  readOnlyRootFilesystem: false
