apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator-prometheus-node-exporter
  labels:
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/instance: prometheus-operator
  namespace: monitoring
imagePullSecrets: []
