apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-prometheus-node-exporter
  annotations:
    prometheus.io/scrape: "true"
  labels: &labels
    jobLabel: node-exporter
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/instance: prometheus-operator
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 9100
      protocol: TCP
      name: metrics
  selector:
    <<: *labels
