---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-scripts
  namespace: minecraft
  labels:
    app.kubernetes.io/name: minecraft
data:
  daily.sh: |
    #!/bin/sh
    export DST=/backup/daily

    ### Remove oldest daily backup if there are 7 or more
    [ `ls ${DST} | wc -l` -gt 6 ] && rm -f ${DST}/$(ls -t ${DST} | tail -n 1)

    ### Create a new daily backup
    apk add xz
    export DATE=$(date +%s)
    export FILENAME=minecraft-vanilla-${DATE}.tar.xz
    tar cJvf ${DST}/${FILENAME} -C /pvc config/ server/
  weekly.sh: |
    #!/bin/sh
    export DST=/backup/weekly
    export SRC=/backup/daily

    ### Remove oldest weekly backup if there are 12 or more
    [ `ls ${DST} | wc -l` -gt 11 ] && rm -f ${DST}/$(ls -t ${DST} | tail -n 1)

    ### Copy oldest daily backup (if one exists) into weekly backups
    [ `ls ${SRC} | wc -l` -gt 0 ] && cp ${SRC}/$(ls -t ${SRC} | tail -n 1) ${DST}
  monthly.sh: |
    #!/bin/sh
    export DST=/backup/monthly
    export SRC=/backup/weekly

    ### Remove oldest monthly backup if there are 12 or more
    [ `ls ${DST} | wc -l` -gt 11 ] && rm -f ${DST}/$(ls -t ${DST} | tail -n 1)

    ### Copy oldest weekly backup (if one exists) into monthly backups
    [ `ls ${SRC} | wc -l` -gt 0 ] && cp ${SRC}/$(ls -t ${SRC} | tail -n 1) ${DST}
