---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bedrock
  namespace: minecraft
  labels:
    app.kubernetes.io/instance: bedrock
    app.kubernetes.io/name: minecraft
spec:
  storageClassName: rook-ceph-fs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bedrock
  namespace: minecraft
  labels:
    app.kubernetes.io/instance: bedrock
    app.kubernetes.io/name: minecraft

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bedrock
  namespace: minecraft
  labels:
    app.kubernetes.io/instance: bedrock
    app.kubernetes.io/name: minecraft
data:
  server.properties: |
    difficulty=normal
    enforce-whitelist=true
    server-name=Hannah Family Minecraft - Bedrock
  permissions.json: |
    [
      {
        "permission": "operator",
        "xuid": "00090000011D14B1"
      }
    ]
  whitelist.json: |
    [
      {
        "name": "FragPenguin89",
        "xuid": "00090000011D14B1"
      }
    ]

---
apiVersion: v1
kind: Service
metadata:
  name: bedrock
  namespace: minecraft
  labels: &labels
    app.kubernetes.io/instance: bedrock
    app.kubernetes.io/name: minecraft
  annotations:
    external-dns.alpha.kubernetes.io/hostname: bedrock.mc.hannahs.family
spec:
  clusterIP: None
  ports:
    - name: minecraft
      port: 19132
      protocol: UDP
  selector:
    <<: *labels

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bedrock
  namespace: minecraft
  labels: &labels
    app.kubernetes.io/instance: bedrock
    app.kubernetes.io/name: minecraft
spec:
  serviceName: bedrock
  replicas: 1
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      serviceAccountName: bedrock
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: minecraft
              weight: 1
      containers:
        - name: minecraft
          image: roemer/bedrock-server:1.12.1.1
          ports:
            - name: minecraft
              containerPort: 19132
              hostPort: 19132
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /bedrock-server/config
            - name: worlds
              mountPath: /bedrock-server/worlds
      volumes:
        - name: config
          configMap:
            name: bedrock
        - name: worlds
          persistentVolumeClaim:
            claimName: bedrock
