---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vanilla
  namespace: minecraft
  labels:
    app.kubernetes.io/instance: vanilla
    app.kubernetes.io/name: minecraft
spec:
  storageClassName: rook-ceph-fs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vanilla-init
  namespace: minecraft
  labels:
    app.kubernetes.io/instance: vanilla
    app.kubernetes.io/name: minecraft
data:
  init.sh: |
    #!/bin/sh

    apk add xz
    tar xJvf /minecraft-vanilla.tar.xz -C /pvc
    chown -R 1000:1000 /pvc/*

---
apiVersion: batch/v1
kind: Job
metadata:
  name: vanilla-init
  namespace: minecraft
  labels:
    app.kubernetes.io/instance: vanilla
    app.kubernetes.io/name: minecraft
spec:
  backoffLimit: 3
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: tapu-koko
      restartPolicy: Never
      containers:
        - name: init
          image: alpine
          command:
            - sh
            - /init.sh
          volumeMounts:
            - name: init
              mountPath: /init.sh
              subPath: init.sh
            - name: pvc
              mountPath: /pvc
            - name: xz
              mountPath: /minecraft-vanilla.tar.xz
      volumes:
        - name: init
          configMap:
            name: vanilla-init
        - name: pvc
          persistentVolumeClaim:
            claimName: vanilla
        - name: xz
          hostPath:
            path: /home/ansible/minecraft-vanilla-1570135874.tar.xz
            type: File

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vanilla
  namespace: minecraft
  labels:
    app.kubernetes.io/instance: vanilla
    app.kubernetes.io/name: minecraft

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vanilla
  namespace: minecraft
  labels:
    app.kubernetes.io/instance: vanilla
    app.kubernetes.io/name: minecraft
data:
  eula.txt: |
    eula=true
  server.properties: |
    difficulty=normal
    enforce-whitelist=true
    motd=Hannah Family Minecraft - Vanilla (Survival)
    enable-rcon=true
  whitelist.json: |
    [
      {
        "uuid": "aedf3044-aaed-40cf-8ac3-2eb19ea89e59",
        "name": "FragPenguin"
      },
      {
        "uuid": "11d158b7-df6d-409c-a6a4-39afc5ec3985",
        "name": "Jay51617"
      },
      {
        "uuid": "f63dcac9-344f-4dcf-a7e9-68005d6ac204",
        "name": "Koji31"
      }
    ]

---
apiVersion: v1
kind: Service
metadata:
  name: vanilla
  namespace: minecraft
  labels: &labels
    app.kubernetes.io/instance: vanilla
    app.kubernetes.io/name: minecraft
  annotations:
    external-dns.alpha.kubernetes.io/hostname: vanilla.mc.hannahs.family
spec:
  type: NodePort
  ports:
    - name: minecraft
      port: 25565
      nodePort: 30100
      targetPort: minecraft
    - name: rcon
      port: 25575
      nodePort: 30101
      targetPort: rcon
  selector:
    <<: *labels

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vanilla
  namespace: minecraft
  labels: &labels
    app.kubernetes.io/instance: vanilla
    app.kubernetes.io/name: minecraft
spec:
  serviceName: vanilla
  replicas: 0
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
      annotations:
        vault.security.banzaicloud.io/vault-role: minecraft__vanilla
        vault.security.banzaicloud.io/vault-skip-verify: "true"
    spec:
      serviceAccountName: vanilla
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: minecraft
                topologyKey: kubernetes.io/hostname
              weight: 1
      securityContext:
        fsGroup: 1000
      containers:
        - name: minecraft
          image: hannahsfamily/mc-server-vanilla:1.14.4
          ports:
            - name: minecraft
              containerPort: 25565
            - name: rcon
              containerPort: 25575
          env:
            - name: JVM_MEM_INIT
              value: 1024M
            - name: JVM_MEM_MAX
              value: 4096M
            - name: RCON_PASSWORD
              value: vault:secrets/data/minecraft/vanilla/rcon#rcon_password
          livenessProbe:
            tcpSocket:
              port: 25565
          readinessProbe:
            tcpSocket:
              port: 25565
          resources:
            requests:
              cpu: 1
              memory: 1024Mi
            limits:
              cpu: 3
              memory: 4096Mi
          volumeMounts:
            - name: storage
              mountPath: /opt/minecraft/config
              subPath: config
            - name: overrides
              mountPath: /opt/minecraft/overrides
            - name: storage
              mountPath: /opt/minecraft/server
              subPath: server
      volumes:
        - name: overrides
          configMap:
            name: vanilla
        - name: storage
          persistentVolumeClaim:
            claimName: vanilla

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vanilla-backup
  namespace: minecraft
  labels:
    app.kubernetes.io/instance: vanilla
    app.kubernetes.io/name: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: batch/v1beta1
kind: CronJobList
items:
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata: &metadata
      name: vanilla-backup-daily
      namespace: minecraft
      labels: &labels
        app.kubernetes.io/instance: vanilla
        app.kubernetes.io/name: minecraft
        app.kubernetes.io/component: backup
    spec:
      schedule: "0 9 * * *"
      concurrencyPolicy: &policy Forbid
      jobTemplate:
        metadata:
          labels:
            <<: *labels
        spec:
          template:
            metadata:
              labels:
                <<: *labels
            spec:
              restartPolicy: Never
              containers:
                - name: backup
                  image: alpine
                  command:
                    - sh
                    - /daily.sh
                  volumeMounts:
                    - name: scripts
                      mountPath: /daily.sh
                      subPath: daily.sh
                      readOnly: true
                    - name: vanilla
                      mountPath: /pvc
                      readOnly: true
                    - name: vanilla-backup
                      mountPath: /backup/daily
                      subPath: daily
              volumes: &volumes
                - name: scripts
                  configMap:
                    name: backup-scripts
                - name: vanilla
                  persistentVolumeClaim:
                    claimName: vanilla
                - name: vanilla-backup
                  persistentVolumeClaim:
                    claimName: vanilla-backup
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      <<: *metadata
      name: vanilla-backup-weekly
    spec:
      schedule: "0 9 * * 0"
      concurrencyPolicy: *policy
      jobTemplate:
        metadata:
          labels:
            <<: *labels
        spec:
          template:
            metadata:
              labels:
                <<: *labels
            spec:
              restartPolicy: Never
              containers:
                - name: backup
                  image: alpine
                  command:
                    - sh
                    - /weekly.sh
                  volumeMounts:
                    - name: scripts
                      mountPath: /weekly.sh
                      subPath: weekly.sh
                      readOnly: true
                    - name: vanilla-backup
                      mountPath: /backup/weekly
                      subPath: weekly
                    - name: vanilla-backup
                      mountPath: /backup/daily
                      subPath: daily
                      readOnly: true
              volumes: *volumes
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      <<: *metadata
      name: vanilla-backup-monthly
    spec:
      schedule: "0 9 1 * *"
      concurrencyPolicy: *policy
      jobTemplate:
        metadata:
          labels:
            <<: *labels
        spec:
          template:
            metadata:
              labels:
                <<: *labels
            spec:
              restartPolicy: Never
              containers:
                - name: backup
                  image: alpine
                  command:
                    - sh
                    - /monthly.sh
                  volumeMounts:
                    - name: scripts
                      mountPath: /monthly.sh
                      subPath: monthly.sh
                      readOnly: true
                    - name: vanilla-backup
                      mountPath: /backup/monthly
                      subPath: monthly
                    - name: vanilla-backup
                      mountPath: /backup/weekly
                      subPath: weekly
                      readOnly: true
              volumes: *volumes
