---
- name: Allow WireGuard connections from peers
  ufw:
    rule: allow
    port: "{{ group.value.port }}"
    src: "{{ hostvars[peer].ansible_facts.default_ipv4.address }}"
    proto: udp
  loop: "{{ groups.all }}"
  loop_control:
    loop_var: peer
  when: hostvars[peer].wireguard[group.key] is defined and peer != inventory_hostname

- name: Install WireGuard config file
  template:
    src: etc/wireguard/interface.conf.j2
    dest: /etc/wireguard/{{ group.value.interface }}.conf
    owner: root
    group: root
    mode: 0600
  register: wg_config

- name: Run wg-quick
  command: wg-quick up {{ group.value.interface }}
  when: wg_config.changed

- name: Enable WireGuard on startup
  service:
    name: wg-quick@{{ group.value.interface }}
    state: restarted
    enabled: true
