---
- name: Add WireGuard PPA
  become: true
  apt_repository:
    repo: ppa:wireguard/wireguard

- name: Install WireGuard
  become: true
  package:
    name: wireguard
    state: present

- name: Allow WireGuard connections from peers
  become: true
  ufw:
    rule: allow
    direction: in
    src: "{{ hostvars[item].ansible_facts.default_ipv4.address }}"
  loop: "{{ groups[wireguard_group] }}"

- name: Allow connections over WireGuard network
  become: true
  ufw:
    rule: allow
    direction: in
    src: 10.4.0.0/24
