---
- name: Add WireGuard PPA
  become: true
  apt_repository:
    repo: ppa:wireguard/wireguard

- name: Install WireGuard
  become: true
  package:
    name: wireguard
    state: present

- name: Allow WireGuard connections from peers
  become: true
  ufw:
    rule: allow
    port: "{{ wireguard_port }}"
    src: "{{ hostvars[item].ansible_facts.default_ipv4.address }}"
    proto: udp
  loop: "{{ groups[wireguard_group] }}"
