---
- name: Add WireGuard PPA
  become: true
  apt_repository:
    repo: ppa:wireguard/wireguard

- name: Install WireGuard
  become: true
  package:
    name: wireguard
    state: present

- include_tasks:
    file: group.yml
    apply:
      become: true
  loop: "{{ wireguard | dict2items }}"
  loop_control:
    loop_var: group
