{
 "title": "Nodes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_utilisation:avg1m",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(node:node_cpu_utilisation:avg1m) / count(node:node_cpu_utilisation:avg1m)"
    }
   ]
  },
  {
   "title": "Load Average (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(node) (node_load1{job=\"node-exporter\"} * on(namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:)",
     "legendFormat": "{{ node }}"
    },
    { "expr": " node:node_num_cpu:sum" }
   ]
  },
  {
   "title": "Load Average (5m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(node) (node_load5{job=\"node-exporter\"} * on(namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:)",
     "legendFormat": "{{ node }}"
    },
    { "expr": " node:node_num_cpu:sum" }
   ]
  },
  {
   "title": "Load Average (15m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(node) (node_load15{job=\"node-exporter\"} * on(namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:)",
     "legendFormat": "{{ node }}"
    },
    { "expr": " node:node_num_cpu:sum" }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "node:node_memory_utilisation:", "legendFormat": "{{ node }}" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "sum(node:node_memory_bytes_total:sum - node:node_memory_bytes_available:sum) / sum(node:node_memory_bytes_total:sum)"
    }
   ]
  }
 ]
}
{
 "title": "Pods",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "kube_node_info{job=\"kube-state-metrics\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod!=\"\",node=~\"$node\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod!=\"\",node=~\"$node\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}