---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels: &labels
    app.kubernetes.io/app: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/component: node-exporter
  name: node-exporter
  namespace: monitoring
  annotations:
    fluxcd.io/tag.node-exporter: semver:~0
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      <<: *labels
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      serviceAccountName: node-exporter
      containers:
        - name: node-exporter
          image: prom/node-exporter:v0.18.1
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
          ports:
            - name: metrics
              containerPort: 9100
              hostPort: 9100
          resources:
            limits:
              cpu: 200m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 30Mi
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
      hostNetwork: true
      hostPID: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: node-exporter
  labels:
    app.kubernetes.io/app: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/component: node-exporter
  namespace: monitoring
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - configMap
    - hostPath
    - secret
  allowedHostPaths:
    - pathPrefix: /proc
      readOnly: true
    - pathPrefix: /sys
      readOnly: true
  hostNetwork: true
  hostPID: true
  hostIPC: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
  hostPorts:
    - min: 1
      max: 65535
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: node-exporter
  labels:
    app.kubernetes.io/app: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/component: node-exporter
  namespace: monitoring
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - node-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-exporter
  labels:
    app.kubernetes.io/app: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/component: node-exporter
  namespace: monitoring
roleRef:
  kind: Role
  name: node-exporter
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: node-exporter
    namespace: monitoring
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels: &labels
    app.kubernetes.io/app: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/component: node-exporter
  name: node-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    <<: *labels
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/app: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/component: node-exporter
  name: node-exporter
  namespace: monitoring
