---
- name: Install pip
  become: true
  package:
    name: python3-pip
    state: present

- name: Install Python OpenShift package
  become: true
  pip:
    name: openshift
    state: present

- name: Get k3s installation script
  become: true
  get_url:
    url: https://get.k3s.io
    dest: "{{ k3s_install_bin_dir }}/{{ k3s_install_name | default('k3s', true) }}-install.sh"
    mode: 0755
    owner: root
    group: root

- name: Run k3s installation script
  become: true
  command: k3s-install.sh
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    INSTALL_K3S_BIN_DIR: "{{ k3s_install_bin_dir }}"
    INSTALL_K3S_SYSTEMD_DIR: "{{ k3s_install_systemd_dir }}"
    INSTALL_K3S_EXEC: |
      {{ k3s_command }} {{ k3s_command_args | join(" ") }}{{ " " }}
      {%- for key, value in k3s_node_labels.items() -%}
        --node-label {{ key }}={{ value }}{{ " " }}
      {%- endfor -%}
      {%- for key, value in k3s_node_taints.items() -%}
        --node-taint {{ key }}={{ value }}{{ " " }}
      {%- endfor -%}
    INSTALL_K3S_NAME: "{{ k3s_install_name | default('', true) }}"
    INSTALL_K3S_TYPE: "{{ k3s_install_type | default('', true) }}"
    K3S_CLUSTER_SECRET: "{{ k3s_cluster_secret | default('', true) }}"
    K3S_URL: "{{ k3s_url }}"
