---
apiVersion: v1
kind: Secret
metadata:
  name: storageos-api
  namespace: storageos-operator
  labels:
    app.kubernetes.io/name: storageos-operator
    app.kubernetes.io/instance: storageos

---
apiVersion: storageos.com/v1
kind: StorageOSCluster
metadata:
  name: storageos
  namespace: storageos-operator
  labels:
    app.kubernetes.io/name: storageos-operator
    app.kubernetes.io/instance: storageos
spec:
  secretRefName: storageos-api
  secretRefNamespace: storageos-operator
  k8sDistro: kubernetes
  csi:
    enable: true
    deploymentStrategy: deployment
  images:
    nodeContainer: storageos/node:1.4.0
  nodeSeletorTerms:
    - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: DoesNotExist
  resources:
    requests:
      memory: 256Mi
