kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-operator-grafana-clusterrolebinding
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus-operator
subjects:
  - kind: ServiceAccount
    name: prometheus-operator-grafana
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: prometheus-operator-grafana-clusterrole
  apiGroup: rbac.authorization.k8s.io
