apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-operator-grafana-datasource
  labels:
    grafana.com/datasource: "1"
    app.kubernetes.io/name: prometheus-operator-grafana
    app.kubernetes.io/instance: prometheus-operator
  namespace: monitoring
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-operator-prometheus:9090/
        access: proxy
        isDefault: true
