apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus-operator
  name: prometheus-operator-grafana
  namespace: monitoring
