---
dependencies:
  - role: ufw
    vars:
      ufw_rules:
        - default: allow
          direction: routed
        - rule: allow
          src: 10.42.0.0/16
  - role: ufw
    vars:
      ufw_rules:
        - rule: allow
          port: "6443"
          proto: tcp
    when: k3s_command == "server"
