---
- name: Install aptitude
  become: true
  package:
    name: aptitude
    state: present
    install_recommends: false

- name: Upgrade packages
  become: true
  apt:
    update_cache: true
    upgrade: full

- name: Autoremove
  become: true
  apt:
    autoremove: true
    purge: true

- name: Autoclean
  become: true
  apt:
    autoclean: true

- name: Check for reboot sentinel
  stat:
    path: "{{ apt_reboot_sentinel }}"
  register: sentinel
  changed_when: sentinel.stat.exists
  notify: Reboot
