---
- name: Install aptitude
  become: true
  package:
    name: aptitude
    state: present
    install_recommends: false

- include_tasks: upgrade.yml
  when: apt_do_upgrade

- include_tasks: unattended_upgrades.yml
  when: apt_unattended_upgrades
