apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: prometheus-operator-alertmanager
  labels:
    app.kubernetes.io/name: prometheus-operator-alertmanager
    app.kubernetes.io/instance: prometheus-operator
  namespace: monitoring
spec:
  baseImage: quay.io/prometheus/alertmanager
  version: v0.19.0
  replicas: 2
  listenLocal: false
  serviceAccountName: prometheus-operator-alertmanager
  externalUrl: https://alerts.metrics.hannahs.family
  paused: false
  logFormat: logfmt
  logLevel: info
  retention: 120h
  routePrefix: /
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
