kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-operator-alertmanager
  labels:
    app.kubernetes.io/name: prometheus-operator-alertmanager
    app.kubernetes.io/instance: prometheus-operator
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - prometheus-operator-alertmanager
